console.log("aaabbb")
console.log('asdsadsa')
console.log(5555)
console.log(2312.231312)
console.log("aaa'bbb")
console.log("aaa'bbb")
console.log(true)
console.log(false)
console.log(5+6)
console.log(5-6)
console.log(5*6)
console.log('5'+'6')
console.log('5'-'6')
console.log('5'*'6')
console.log("5"+"6")

console.log("ABC"*"XYZ")
console.log("ABC"+"XYZ")

console.log(8 ** 3)
console.log(9 & 4)